'''
Created on Jan 23, 2012

@author: yati
'''
FRAMES_PER_SECOND = 60
NUM_INPUTS = 4
NUM_HIDDEN = 1
NEURONS_PER_HIDDEN = 6
NUM_OUTPUTS = 2
ACTIVATION_RESPONSE = 1
BIAS = -1
MAX_TURN_RATE = 0.3
MAX_SPEED = 2
SWEEPER_SCALE = 5
NUM_MINES = 40
NUM_SWEEPERS = 30
NUM_TICKS = 2000
MINE_SCALE = 2
CROSSOVER_RATE = 0.7
MUTATION_RATE = 0.1
MAX_PERTURBATION = 0.3
NUM_ELITE = 4
NUM_COPIES_ELITE = 1
WINDOW_WIDTH, WINDOW_HEIGHT = 800, 400


